backend:
  replicaCount: 3
  image:
    repository: backend
    tag: local
    pullPolicy: Never
  port: 5000
  resources:
    requests:
      cpu: "20m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

frontend:
  replicaCount: 1
  image:
    repository: frontend
    tag: local
    pullPolicy: Never
  port: 80

mongodb:
  image:
    repository: mongo
    tag: "7"
  port: 27017
  storage: 1Gi
  username: notesadmin
  password: ChangeThisPassword123

ingress:
  host: notes.local