apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "{{ .Values.backend.port }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: { { .Values.backend.replicaCount } }
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.36
          command:
            - sh
            - -c
            - "until nc -z mongodb 27017; do echo waiting for mongodb; sleep 2; done"
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: { { .Values.backend.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.backend.port } }
          resources: { { - toYaml .Values.backend.resources | nindent 12 } }
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: APP_VERSION
              value: "{{ .Values.backend.appVersion }}"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
            - name: MONGODB_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASS)@mongodb:27017/notesdb?authSource=admin"
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: { { .Values.backend.port } }
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: { { .Values.backend.port } }
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: { { .Values.backend.port } }
      targetPort: { { .Values.backend.port } }
